name: ci-cd

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-cd.yaml
      - src/pydeconv/**
      - tests/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  quality-and-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python }}
        run: uv python install ${{ matrix.python }}

      - name: Install the project
        run: uv sync --all-extras --no-group docs

      - name: Quality checks
        run: uv run pre-commit run --all-files

      - name: run-tests
        if: matrix.python != '3.10'
        run: uv run pytest --cov=PyDeconv
