name: docs

on:
  push:
    branches: 'main'

jobs:
  deploy-docs:
    if: (github.event_name == 'release') || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        env:
          UV_INDEX_OWKIN_USERNAME: ${{ steps.auth.outputs.username }}
          UV_INDEX_OWKIN_PASSWORD: ${{ steps.auth.outputs.password }}
        run: uv sync --all-extras --group docs

      - name: deploy-to-gh-pages
        run: uv run mkdocs gh-deploy --force
